import type { Metadata } from "next";
import "./globals.css";

import { Kanit } from "next/font/google";

import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";

import { Header } from "@/components/header";
const kanit = Kanit({
    subsets: ["latin"],
    // display: "swap",
    variable: "--font-kanit",
    weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={kanit.variable}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    disableTransitionOnChange
                >
                    <Header />
                    <main className="mt-20">
                        <div className="h-full w-full dark:bg-black bg-white dark:bg-grid-small-white/[0.2] bg-grid-small-black/[0.2] relative flex items-center justify-center">
                            {children}
                        </div>
                    </main>
                    <Toaster />
                    {/* <Footer /> */}
                </ThemeProvider>
            </body>
        </html>
    );
}
